version: '3.8'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - ./volumes/keycloak-data:/opt/keycloak/data
    command: start-dev
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./volumes/keycloak-db:/var/lib/postgresql/data

  resource-server:
    build: ./resource-server
    container_name: resource-server
    ports:
      - "5001:5001"
    depends_on:
      - db
      - keycloak

  frontend-spa:
    build: ./frontend-spa
    container_name: frontend-spa
    ports:
      - "3000:3000"
    depends_on:
      - resource-server
      - keycloak

  frontend-ssr:
    build: ./frontend-ssr
    container_name: frontend-ssr
    ports:
      - "4000:4000"
    depends_on:
      - resource-server
      - keycloak

  backend2backend-client:
    build: ./b2b-client
    container_name: backend2backend-client
    depends_on:
      - resource-server
      - keycloak

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: car_rental
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: rental
    volumes:
      - ./volumes/car-rental-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
